#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import Window kivy.core.window.Window
#:import FadeTransition kivy.uix.screenmanager.FadeTransition



<ArrowButton@MDIconButton>
    pos_hint: {"center_x": 0.4 , "center_y": 0.5}
    theme_text_color: "Custom"
    text_color: 0,0,0,0
    background_color: 0,0,0,0


<MenuButton@ArrowButton>
    pos_hint: {"center_x": 0.87 , "center_y": 0.95}
<MenuImage@Image>
    pos_hint: {"center_x": 0.87 , "center_y": 0.95}
    source: 'menu.png'
<BackButton@ArrowButton>
    pos_hint: {"center_x": 0.15 , "center_y": 0.95}
    on_press: app.go_to("back")
<BackImage@Image>
    pos_hint: {"center_x": 0.15 , "center_y": 0.95}
    source: 'back_btn.png'
<SignoutButton@MenuButton>
    size_hint: None, None
    halign: "center"
    md_bg_color: get_color_from_hex("#FDFAF7")
    pos_hint: {"center_x": .15 , "center_y": .95}
    on_release: app.go_to('login')
    font_style: 'Button'
<SignoutLabel@Label>
    text: "sign out"
    pos_hint: {"center_x": .15 , "center_y": .95}
    color: 0,0,0,1
    bold: True

<SignoutImage@Image>


<OpenCard@MDCard>
    orientation: "vertical"
    padding: 10
    md_bg_color: get_color_from_hex("#FFFFFF")
    size_hint: 0.8 , 0.35
    elevation: 5
    radius: [10]

<ClosedCard@MDCard>
    orientation: "vertical"
    padding: 10
    md_bg_color: get_color_from_hex("#FFFFFF")
    size_hint: 0.8 , 0.07
    elevation: 1
    radius: [10]




#******************** NAVBAR ***********************

<BottomNavbarCard@MDCard>
    md_bg_color: get_color_from_hex("#FFFFFF")
    size_hint: None , None
    pos_hint: {"center_x": 0.5, "center_y": 0.05}
    elevation: 6
    radius: [10]
    orientation: "horizontal"
    padding: 10
    halign: "center"
    valign: "center"
    size_hint: 1 , 0.15
<BoxForButton@MDBoxLayout>
    pos_hint: {"center_x": 0.5 , "center_y": 0.9}
<BottomNavbarButton@MDIconButton>
    theme_text_color: "Custom"
    text_color: 0,0,0,0
    background_color: 0,0,0,0
    halign: "center"
    valign: "center"
<NavBarImage@Image>
    size_hint: 1 , 1

<NavbarBox@MDBoxLayout>
    md_bg_color: 0,0,0,0
    orientation: "horizontal"
    size_hint: 1 , 0.1
    pos_hint: {"center_x": 0.5, "center_y": 0.05}
<ButtonBox@MDFloatLayout>
    pos_hint: {"center_x": 0.5 , "center_y": 0.5}

<HomeButton@MDIconButton>
    on_release: app.go_to('home')
    pos_hint: {"center_x": 0.5 , "center_y": 0.5}
<ProfileButton@MDIconButton>
    on_release: app.go_to('profile')
    pos_hint: {"center_x": 0.5 , "center_y": 0.5}

<DailyButton@MDIconButton>
    on_release: app.go_to('daily')
    pos_hint: {"center_x": 0.5 , "center_y": 0.5}
<DiagnoseButton@MDIconButton>
    on_release: app.go_to('diagnose')
    pos_hint: {"center_x": 0.5 , "center_y": 0.5}









#******************** LOGIN PAGE *******************

<LoginLayout@MDFloatLayout>
    md_bg_color: get_color_from_hex("#012241")
    orientation: 'vertical'

<LoginHeaderLabel@MDLabel>
    halign: "left"
    font_style: "H4"
    bold: True
    color: get_color_from_hex("#FFBA99")


<LoginGeneralLabel@MDLabel>
    halign: "left"
    color: 1,1,1,1
    font_style: 'Body2'

<LoginLabelCard@MDCard>
    orientation: "vertical"
    theme_text_color: "Custom"
    md_bg_color: 0,0,0,0
    size_hint: 0.9 , 0.08
    elevation: 0

<LoginInputCard@MDCard>
    orientation: "vertical"
    padding: 10
    md_bg_color: get_color_from_hex("#FFFFFF")
    size_hint: 0.9 , 0.08
    elevation: 3
    radius: [20]

<LoginInputField@MDTextField>
    halign: "center"
    pos_hint: {"center_x": 0.55, "center_y": 0.53}
    foreground_color: 0,0,0,1

<LoginButton@MDCard>
    orientation: "vertical"
    padding: 10
    md_bg_color: get_color_from_hex("#FFBA99")
    size_hint: 0.9 , 0.08
    elevation: 3
    radius: [20]
<LoginButtonLabel@MDLabel>
    halign: "center"
    bold: True
    pos_hint: {"center_x": 0.55, "center_y": 0.53}
    color: 1,1,1,1

<LoginSocialIcon@MDIconButton>
    halign: "center"
    size: self.parent.size
    user_font_size: "5sp"
    pos_hint: {"center_x": 0.57, "center_y": 0.5}

<LoginFooter@LoginLabelCard>
    pos_hint: {"center_x": 0.5, "center_y": 0.02}
<LoginFooterLabel@MDLabel>
    halign: "center"
    color: 1,1,1,1
    font_style: 'Caption'



#******************** PROFILE PAGE *******************


<ProfilePageLayout@MDFloatLayout>
    md_bg_color: get_color_from_hex("#FDFAF7")
    orientation: 'vertical'

<UserImage@Image>
    halign: "center"
    source: 'user.png'
    size_hint_y: 0.14
    allow_stretch: True
    pos_hint: {"center_x": 0.5 , "center_y": 0.85}

<UserNameLabel@MDLabel>
    text: "Dana Cohen"
    halign: "center"
    color: 0,0.439,0.313,1
    bold: True
    pos_hint: {"center_x": 0.5 , "center_y": 0.75}
    font_style: "H6"


<EditIcon@ArrowButton>
    halign: "center"
    pos_hint: {"center_x": 0.625 , "center_y": 0.85}
    on_press: app.go_to('profile_security')

<CardContentBox@MDBoxLayout>
    spacing: 10
    orientation: "horizontal"
<CardContentImage@Image>
    halign: "left"
    size_hint: None , None
    width: 45
    pos_hint: {"center_x": 0.1 , "center_y": 0.5}
<CardContentLabel@MDLabel>
    color: 0,0,0,1
    bold: True
    font_style: "Body1"

# Fields
<LeftLabel@MDLabel>
    halign: "left"
    color: 0,0,0,1
    font_style: "Body2"
<RightLabel@MDLabel>
    halign: "right"
    color: 0,0,0,0.4
    font_style: "Body2"
<SecurityInputField@MDTextField>
    halign: "left"
    pos_hint: {"center_x": 0.55, "center_y": 0.53}
    foreground_color: 0,0,0,1
    font_style: "Body2"



#******************** HOME PAGE *******************

<SmallUserImage@Image>
    id: user_img
    halign: "center"
    source: 'user.png'
    size_hint_y: 1
    allow_stretch: True
    pos_hint: {"center_x": 0.2 , "center_y": 0.5}

<HomeNameLabel@MDLabel>
    id: user_name
    text: "Hello Dana"
    halign: "left"
    color: 0,0.439,0.313,1
    pos_hint: {"center_x": 0.5 , "center_y": 0.2}
    font_style: "Body1"

<HomeGreet@MDLabel>
    text: "Welcome Back!"
    pos_hint: {"center_x": 0.5 , "center_y": 0.65}
    halign: "left"
    color: 0,0.439,0.313,1

    font_style: "Body1"

<TwoCardsLayout@OpenCard>

    orientation: "horizontal"
    size_hint: 1, 0.25
    theme_text_color: "Custom"
    md_bg_color: 0,0,0,0
    elevation: 0

<LabelLeftBoxLayout@MDBoxLayout>
    orientation: "vertical"
    pos_hint: {"center_x": 0.5 , "center_y": 0.5}
    size_hint: 0.6 , 1
    halign: "center"

<LabelRightBoxLayout@MDBoxLayout>
    orientation: "vertical"
    pos_hint: {"center_x": 0.5 , "center_y": 0.2}
    size_hint: 0.6 , 1
    halign: "center"

<HomeButtonLabelLight@MDLabel>
    halign: "center"
    color: 1,1,1,1
    bold: True
    font_style: 'Body2'


<HomeButtonLabelDark@MDLabel>
    halign: "center"
    color: 0,0,0,1
    bold: True
    font_style: 'Body2'

<HomeCardForImage@MDCard>
    pos_hint: {"center_x": 0.5 , "center_y": 0.7}
    halign: "center"
    orientation: "horizontal"
    size_hint_y: 0.11
    elevation: 0
    theme_text_color: "Custom"
    md_bg_color: 0,0,0,1

<HomeLeftImage@FitImage>
    pos_hint: {"center_x": 0.5 , "center_y": 0.7}
    size_hint: None , None
    width: 140
    height: 140
    allow_stretch: True

<HomeRightImage@Image>
    pos_hint: {"center_x": 0.5 , "center_y": 0.4}
    size_hint: None , None
    width: 140
    height: 140
    allow_stretch: True



#******************** QUESTION PAGE *******************

<CountImage@Image>
    source: 'count_1.png'
    pos_hint: {"center_x": .5 , "center_y": 0.9}

<QuestionImage@Image>
    source: 'Q1.png'
    pos_hint: {"center_x": .5 , "center_y": 0.65}

<QuestionNumber@MDLabel>
    text: "QUESTION 1 OF 9"
    halign: "left"
    pos_hint: {"center_x": .6 , "center_y": 0.47}
    font_style: "Body2"
    color: 0.498,0.56,0.611,1
    bold: True

<QuestionButton@LoginButton>
    md_bg_color: get_color_from_hex("#FFFFFF")
    size_hint: 0.6 , 0.07
    padding: 10
<QuestionButtonLabel@MDLabel>
    halign: "center"
    color: 0,0,0,1
    bold: True
    font_style: 'H5'



#******************** HOME PAGE *******************

<CenterdCardForText@OpenCard>
    halign: "center"
    orientation: "horizontal"
    pos_hint: {"center_x": 0.5 , "center_y": 0.87}
    size_hint_y: 0.11
    elevation: 0
    theme_text_color: "Custom"
    md_bg_color: 0,0,0,0



#******************** DIAGNOSE PAGE *******************


#******************** DAILY PAGE *******************

<ProgressCard@ClosedCard>
    size_hint: 1 , 0.09
    halign: "center"
    pos_hint: {"center_x": 0.5}
    padding: 15

<DailyPrecent@MDLabel>
    size_hint: 0.25 , 1
    font_style: 'Body1'
    color: 0,0,0,0.4
<ProgressLabel@MDLabel>
    halign: "left"
    font_style: 'Body1'
    color: 0,0,0,1
    bold: True
<ProgressBox@MDBoxLayout>
    spacing: 20
    orientation: "vertical"

<DailyProgressBar@MDProgressBar>
    value: 20
    color: 0,0,0,1

<DailyMainBody@MDBoxLayout>
    spacing: 20
    size_hint: 0.9 , 0.8
    orientation: "vertical"
    halign: "center"
    pos_hint: {"center_x": 0.5 , "center_y": 0.43}

















