#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import Window kivy.core.window.Window
#:include classes_test.kv


Screen:
    name: 'loading'
    MDBoxLayout:
        md_bg_color: get_color_from_hex("#F5E5D6")
        orientation: "vertical"
        size_hint: 1 , 1
        Image:
            pos_hint: {"center_x": 0.5}
            source: 'loading-logo.png'
            size_hint: 0.9, 1

        Image:
            source: 'loading-text.png'