#:import get_color_from_hex kivy.utils.get_color_from_hex
#:import Window kivy.core.window.Window

<DemoProject>:
    Screen:
        name: 'loading'
        on_enter: app.go_to('login')
        MDBoxLayout:
            padding: 20
            md_bg_color: get_color_from_hex("#F5E5D6")
            orientation: 'vertical'
            Image:
                source: 'images\loading-logo.png'
                size_hint_y: 0.5
            Image:
                source: 'images\loading-text.png'